import type { Metadata } from "next";
import { Libre_Franklin as Prompt } from "next/font/google";
import "./globals.css";
import LeftBar from "../components/LeftBar";
// import RightBar from "../components/RightBar";

const prompt = Prompt({
  subsets: ["latin"],
  weight : ["100","200","300","400","500","600","700","800","900"],
});



export const metadata: Metadata = {
  title: "My Name App",
  description: "Generated by Thayakorn eiei",
  keywords: ['Name', 'App','ชื่อ'],
  icons:{
    icon:'/vercel.svg',
  },
  authors:[{
    name:"Thayakorn SAU",
    url:"https://github.com/ThayakornSAU",
  }]  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
      <body className={prompt.className + "text-white"}>
        <div className="min-h-screen relative">
          <div className="fixed left-10 top-1/2 transform -translate-y-1/2 z-40">
            <LeftBar />
          </div>
          <div className="px-4 md:px-80">
            <main className="py-8 max-w-full">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
